language: python
python:
- 3.7
os: linux
dist: xenial
cache:
  pip: true

if: type != pull_request AND branch =~ /^(main|manual-.*)$/

install:
- pip install -r requirements.txt

before_script:
- git clone https://github.com/mixxxdj/manual.git manual
- cd manual
- git checkout main

jobs:
  include:
    - name: HTML
      script:
      - sh ../build_html.sh
      before_deploy:
      - npm install -g netlify-cli
      - export PATH="$(npm prefix -g)/bin:$PATH"
      deploy:
        provider: script
        skip_cleanup: true
        script: netlify deploy --prod --dir build/html
        on:
          all_branches: true

    - name: PDF
      script:
      - sh ../build_pdf.sh
      addons:
        apt:
          packages:
            - texlive
            - texlive-xetex
            - texlive-latex-extra
            - latexmk
            - xindy
