language: python
python:
- 3.7
os: linux
dist: focal
cache:
  pip: true

if: type != pull_request AND branch =~ /^(manual-)/

install:
- pip install -r requirements.txt

before_script:
- git clone https://github.com/mixxxdj/manual.git manual
- cd manual
- git branch -r
- export LATEST_BRANCH="$(git branch -r | grep -Po 'origin/manual-\d+\.\d+\.x' | sort | tail -n 1)"
- echo "Building from branch ${LATEST_BRANCH}"
- git checkout "${LATEST_BRANCH}"

jobs:
  include:
    - name: HTML
      script:
      - sh ../build_html.sh
      before_deploy:
      - npm install -g netlify-cli
      - export PATH="$(npm prefix -g)/bin:$PATH"
      deploy:
        provider: script
        skip_cleanup: true
        script: netlify deploy --prod --dir build/html
        on:
          all_branches: true

    - name: PDF
      script:
      - sh ../build_pdf.sh
      addons:
        apt:
          packages:
            - texlive
            - texlive-xetex
            - texlive-latex-extra
            - latexmk
            - xindy

    - name: Qt Help
      before_script:
      - cd "source"
      - export VERSION="$(python -c 'import conf; print(conf.version)')"
      - export LANGUAGES="$(python -c 'import conf; print(" ".join(sorted((lang for lang in conf.supported_languages.keys()), reverse=True)))')"
      - cd ..
      script:
      - for language in ${LANGUAGES};
        do
          mkdir -p "build/qthelp/${language}";
          sphinx-build -b qthelp "-Dqthelp_basename=manual-${language}" "-Dlanguage=${language}" source "build/qthelp/${language}";
          qhelpgenerator "build/qthelp/${language}/manual-${language}.qhcp";
          mv "build/qthelp/${language}/manual-${language}.qhc" "build/qthelp/${language}/manual-${language}.qch" "build/qthelp";
        done
      - cd "build/qthelp/";
      - tar czf "manual-${VERSION}.tar.gz" *.qhc *.qch
      addons:
        apt:
          packages:
            - qhelpgenerator-qt5
